import React from "react";
import { View, Text, ScrollView
 } from "react-native";


export default function AppContacts(){
    return(
        <View>
            <ScrollView
                showsVerticalScrollIndicator={false}
            >
            <Text>App Contacts</Text>
            <Text>
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            loremfewhjuiofhwjwuefhwuifhwefwfwefwehfwuifhw
            </Text>
            </ScrollView>
        </View>
    );
}